### ISSUE TITLE
Console error on reload + Chats not working.

### ISSUE THREAD

**Issue by MithrandirCraft** [James137137/FactionChat#10]
Hello, players are unable to use faction chats, Staff is unable to use staff chats.
Error on console when plugin restarts:
http://hastebin.com/jujehitaze.avrasm

Faction chat version: 1.9.9
Spigot: 1.8.8

**Comment by James137137** [comment]
is this still present?

**Comment by sgdc3** [comment]
@MithrandirCraft

**Comment by MithrandirCraft** [comment]
No I don't think so. Feel free to close it. The only issue right now is this:
https://github.com/James137137/FactionChat/issues/12#issuecomment-168776190

**Comment by James137137** [comment]
ty
