### ISSUE TITLE
Authme compatibility

### ISSUE THREAD

**Issue by MithrandirCraft** [James137137/FactionChat#12]
Hi! Could you please take a look at this?:

https://github.com/Xephi/AuthMeReloaded/issues/259

Thanks!

--------------------------
Current authme version: 5.2-SNAPSHOT-b660
Faction chat version: 1.9.12-SNAPSHOT
Current Minecraft-Spigot version: 1.8.8

**Comment by James137137** [comment]
Thanks MithrandirCraft.

Personally I've tried in the past to removed staff chat as it has nothing to do with Factions but I had too many PMs when I removed it.

i'll see if I can quickly fix it now.

**Comment by James137137** [comment]
Fixed

**Comment by James137137** [comment]
ok It might not be fixed. looking at some of the Hastbin there

**Comment by James137137** [comment]
ok Seems my previous changes would have fixed that error too (http://hastebin.com/imoxiwajem.avrasm)

Going to recompile the plugin using 

http://dev.bukkit.org/bukkit-plugins/authme-reloaded/files/75-auth-me-5-0-beta3/

**Comment by sgdc3** [comment]
James137137 you should use this:
http://ci.xephi.fr/plugin/repository/everything/fr/xephi/authme/5.2-SNAPSHOT/authme-5.2-SNAPSHOT.jar

**Comment by sgdc3** [comment]
it's a maven repo, you can add it to the pom file without putting the jar into the libs folder ;)

**Comment by James137137** [comment]
Thanks. :D

**Comment by James137137** [comment]
I see 

fr.xephi.authme.api.API.isAuthenticated(player) is now @Deprecated

What would you suggest I use?

**Comment by James137137** [comment]
never mind (fr.xephi.authme.api.NewAPI.)

**Comment by James137137** [comment]
ok that's all done. it "should" work find now

**Comment by MithrandirCraft** [comment]
fixed.

**Comment by James137137** [comment]
:-(

**Comment by James137137** [comment]
Well I have:

if ((myplayer.hasPermission("FactionChat.ModChat") || FactionChat.isDebugger(myplayer.getName())) && AuthMeAPI.isLoggedIn(player))

with fr.xephi.authme.api.NewAPI.getInstance().isAuthenticated(player); to check if logged in

The AuthMe stuff is only enabled if this.getServer().getPluginManager().getPlugin("AuthMe") != null

Could you check this?

**Comment by sgdc3** [comment]
Yeah but if I remember well you check if the allowchat option is true or false, can you try to remove this check?

**Comment by James137137** [comment]
ok I think I fixed it.....
http://jenkins.lolnet.co.nz/job/FactionChat/lastSuccessfulBuild/artifact/target/FactionChat.jar

**Comment by MithrandirCraft** [comment]
Can I use this build? :3

**Comment by James137137** [comment]
yes

**Comment by MithrandirCraft** [comment]
thank you <3 I'll report back.

**Comment by MithrandirCraft** [comment]
Well... I can still read messages when logged out.

**Comment by MithrandirCraft** [comment]
Updated affected versions.

**Comment by James137137** [comment]
Ok I tested it myself with only AuthMe, Factions (and massiveCore) and FactionChat.

Unregistered could see ModChat
Registered yet logout could not see ModChat.

Going to fix this now

**Comment by James137137** [comment]
http://jenkins.lolnet.co.nz/job/FactionChat/13/artifact/target/FactionChat.jar

Try that

**Comment by MithrandirCraft** [comment]
Unregistred yet logout?
Well that's just what I tried, and I could see myself spamming moderator chat with another account while logged out with an OP account. (Maybe I could see it because I'm OP?)

In any case, I'm trying your last build, will report asap.

**Comment by James137137** [comment]
make sure it is registered too

**Comment by MithrandirCraft** [comment]
![screenshot_1](https://cloud.githubusercontent.com/assets/6623704/12153754/ef619364-b4bb-11e5-8f2b-62e14eac8c84.png)
![screenshot_2](https://cloud.githubusercontent.com/assets/6623704/12153755/ef78b3d2-b4bb-11e5-824a-b337f8e44b22.png)

**Comment by James137137** [comment]
this is my /fc mod right?

**Comment by MithrandirCraft** [comment]
Those results are using the last build you just gave me.

**Comment by James137137** [comment]
ok with my test it is blocking correctly. I'll make another build that prints in the console some information. Could you paste it here (when it is being bypassed)?

**Comment by James137137** [comment]
@MithrandirCraft

**Comment by MithrandirCraft** [comment]
Hey James, Xephii passed me a build with a pull request he did on FactionChat.

It works fine with it :) So as long as you apply it, the issue should be fixed.

**Comment by James137137** [comment]
ok pulled Thanks @Xephi

**Comment by James137137** [comment]
http://jenkins.lolnet.co.nz/job/FactionChat/16/artifact/target/FactionChat.jar

**Comment by James137137** [comment]
Closed and fixed.
Thanks @MithrandirCraft and @Xephi 

and everyone from
https://github.com/Xephi/AuthMeReloaded/issues/259

**Comment by James137137** [comment]
uploaded to dev.bukkit
