### ISSUE TITLE
GroupManagerX repo

### ISSUE THREAD

**Issue by sgdc3** [James137137/FactionChat#13]
Hello, if you want you can use the GroupManagerX artifact from xephi's repo as dependency ;) (i's just a mavenized version of the latest GroupManager build)

**Comment by sgdc3** [comment]
Thanks ;)

**Comment by James137137** [comment]
now I just need to find one for BanManager, bPermissions and PermissionsEx :-p

**Comment by sgdc3** [comment]
https://pex-repo.aoeu.xyz
bperm is on xephi's repo

**Comment by sgdc3** [comment]
banmanager http://ci.frostcast.net/plugin/repository/everything/

**Comment by James137137** [comment]
[ERROR] Failed to execute goal on project FactionChat: Could not resolve dependencies for project nz.co.lolnet.james137137:FactionChat:jar:1.9.12-SNAPSHOT: Failed to collect dependencies at ru.tehkode:PermissionsEx:jar:1.23.1-SNAPSHOT: Failed to read artifact descriptor for ru.tehkode:PermissionsEx:jar:1.23.1-SNAPSHOT: Could not transfer artifact ru.tehkode:PermissionsEx:pom:1.23.1-SNAPSHOT from/to pex-repo (http://pex-repo.aoeu.xyz/): sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target -> [Help 1]

something was wrong with the https. It doesn't like let's encrypt cert yet :-(
