### ISSUE TITLE
Readd metrics

### ISSUE THREAD

**Issue by sgdc3** [James137137/FactionChat#15]

**Comment by sgdc3** [comment]
P.S: via maven obviously

**Comment by sgdc3** [comment]
@James137137 You need also to shade the metrics package as described here: 
https://github.com/Hidendra/Plugin-Metrics/wiki/Usage

**Comment by James137137** [comment]
I see... ok time to edit some stuff and redo it XD

**Comment by sgdc3** [comment]
Lol still not the right way, i'll send a pr later ;)

**Comment by James137137** [comment]
ok thanks :-p

**Comment by sgdc3** [comment]
@James137137 Lol sorry i forgot about it ;)

**Comment by James137137** [comment]
should I close this now @sgdc3

**Comment by sgdc3** [comment]
Yeah i think you should. xD

**Comment by James137137** [comment]
done
