### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by MithrandirCraft** [James137137/FactionChat#16]
Found this error on logs:
http://hastebin.com/cuxawahoje.avrasm

Spigot version: 1.8.8
Faction chat version: 1.8.12

**Comment by Barrimor** [comment]
Caused by: java.lang.IllegalArgumentException: NPCs are not allowed: CraftPlayer{name=AndresGatoXD}

Do you have an AntiCheat or something that add "Citizens" or else?

**Comment by MithrandirCraft** [comment]
Hmmm I used to have AntiAura (premium spigot) plugin. But I removed it because it's quite buggy. I don't remember if I had it on at that moment, but I think not.

**Comment by MithrandirCraft** [comment]
Now I'm just using NCP, which doesn't use NPC's

**Comment by James137137** [comment]
no idea what the NPC is but I've made a check before hand so it doesn't error. Lets hope it works...

**Comment by MithrandirCraft** [comment]
NCP = NoCheatPlus

**Comment by James137137** [comment]
I think this is fixed now
