### ISSUE TITLE
/fc e ? (not working)

### ISSUE THREAD

**Issue by Barrimor** [James137137/FactionChat#17]
Hello, /fc e is not working for me on the latest version of spigot 1.8.8 REF: git-Spigot-db6de12-930a59c.

/fc a, /fc f, etc.. are working in the right way, but when I type /fc in chat it tells me that there is a command "/fc e" (Error: please....), so maybe it's a typo or an enemy chat for real, IDK.
Please fix that! :)

**Comment by James137137** [comment]
There is a permission node : factionchat.enemychat is that set?
