### ISSUE TITLE
Prefix false in configs

### ISSUE THREAD

**Issue by Barrimor** [James137137/FactionChat#18]
Even with the settings "IncludePrefix" set to false in config and then /fc reload or reboot the server, the prefix will still be shown in the factions (including all privates) chat

**Comment by Maxetto** [comment]
Having this too.
As far as I tested, I tested it only with me, that I have a custom prefix bound to my name (that might be the problem (?))

Spigot 1.8.8
PermissionsEx 1.23.4
Vault 1.5.2
FactionChat 1.9.17

**Comment by James137137** [comment]
FactionChat Version 1.10 might fix this problem
