### ISSUE TITLE
FactionsChat not working on Factions v1.6.9.5 or Spigot #1649

### ISSUE THREAD

**Issue by TheMasteredPanda** [James137137/FactionChat#21]
Yo,

Currently developing a Factions server. I would like to implement FactionsChat into my server but I am failing on finding a compatible version that will work with Factions v1.6.9.5 & Spigot version #1649. 

Mind helping me out?

Thanks,
Panda.

**Comment by James137137** [comment]
are people still using factions 1.6? doesn't 1.6 already have some chat feature.

I removed support for 1.6. I don't mind re-adding it if you want?

Until then I suggest using any FactionChat 1.9.12 and below

**Comment by James137137** [comment]
http://dev.bukkit.org/bukkit-plugins/factionchat/files/112-faction-chat-1-9-10/ should be pretty stable

**Comment by James137137** [comment]
any update @TheMasteredPanda .
