### ISSUE TITLE
FactionChat crash ?

### ISSUE THREAD

**Issue by Blamo27** [James137137/FactionChat#23]
https://www.spigotmc.org/threads/my-server-crash.141585/

**Comment by James137137** [comment]
Thanks for bring this to my attention. I'm not sure if it was the cause of the crash but I can at least ensure that it will not be based on nz.co.lolnet.james137137.FactionChat.FactionsInfoServer.FactionInfoServer$ThreadListenForClients.run(FactionInfoServer.java:52),

**Comment by James137137** [comment]
Fixed. Thanks again. I'll try and release an update on dev.bukkit later tomorrow (NZ time)

**Comment by James137137** [comment]
http://jenkins.lolnet.co.nz/job/FactionChat/80/ is what i'm going to upload tomorrow
