### ISSUE TITLE
make compatible with mcmmo party chat!

### ISSUE THREAD

**Issue by tuanjr** [James137137/FactionChat#24]
When player in /fc a or /fc f, player can't switch to mcmmo party chat (/pc)
they must switch to public  (/fc p) berforce type /pc
Can you make when player in /fc a or /fc f, they can switch directly to mcmmo party chat when type /pc?
sorry my english bad.

**Comment by James137137** [comment]
can you give a link to this plugin?

**Comment by James137137** [comment]
you can play around with the prioity feature (https://github.com/James137137/FactionChat/blob/master/src/main/resources/config.yml#L48) and you might find the sweet spot.

maybe onPlayerChat: 3 might work. I would need to check the plugin tho to confirm

**Comment by tuanjr** [comment]
It's mcmmo,  very popular plugin
https://github.com/mcMMO-Dev/mcMMO

**Comment by James137137** [comment]
yeah. just double checking we are talking about the same plugin :D 

just reading this part of the code atm... https://github.com/mcMMO-Dev/mcMMO/blob/master/src/main/java/com/gmail/nossr50/listeners/PlayerListener.java#L632

i'll reply back in the next 5min

**Comment by James137137** [comment]
going based on its event priority = EventPriority.HIGH, ignoreCancelled = true....

lets try something out before I try and hook into the plugin. (I'm expecting this to somewhat fail)


In FactionChat Config search for "onPlayerChat" and replace the **1** to a **5** and see if everything works correctly. I don't expect it will but by it might by luck XD

**Comment by tuanjr** [comment]
Thank you verymuch :D

**Comment by James137137** [comment]
just incase: http://jenkins.lolnet.co.nz/job/FactionChat/97/

**Comment by tuanjr** [comment]
with factionschat-1.9.19, still won't work. i need update factions chat to latest version?

**Comment by James137137** [comment]
yeah... my jenkins build failed... hold up

**Comment by James137137** [comment]
http://jenkins.lolnet.co.nz/job/FactionChat/99/artifact/target/FactionChat.jar

let me know how works.

**Comment by tuanjr** [comment]
Build 99 won't work, i mean all broken, /fc f, /fc a.....ALL BROKEN.

**Comment by James137137** [comment]
ok I'll have a good debug of it tomorrow

**Comment by James137137** [comment]
how is it now @tuanjr did we manage to test it?

**Comment by tuanjr** [comment]
i'm confirm it work great now! just as i wish.

**Comment by James137137** [comment]
Sweet!
