### ISSUE TITLE
factions title problems

### ISSUE THREAD

**Issue by tuanjr** [James137137/FactionChat#26]
config set like this:

>   FactionChat: '&a{1}{0} {T} &a{2}&8: &2{M}'

if player set factions title, chat show normal, but player does not set factions title
then when player chat in factions chat, chat show like this:

![tttt](http://i.imgur.com/LrOZqqs.png)

**Comment by James137137** [comment]
Could you test this on the lastest build?
http://jenkins.lolnet.co.nz/job/FactionChat/lastSuccessfulBuild/artifact/target/FactionChat.jar

config has changed a bit too so make a quick backup of the config.yml

https://github.com/James137137/FactionChat/blob/master/src/main/resources/config.yml#L76

**Comment by tuanjr** [comment]
Tried latest version, still not fixed!

**Comment by James137137** [comment]
ok thanks. I'll look into it and fix it

**Comment by James137137** [comment]
should be fixed now. could you test it for me @tuanjr 

http://jenkins.lolnet.co.nz/job/FactionChat/101/

**Comment by James137137** [comment]
afterwards I'll push 1.10.0 to dev.bukkit.org

**Comment by tuanjr** [comment]
But build 101 is failed build?

**Comment by tuanjr** [comment]
just test build 101, still not fixed.

**Comment by James137137** [comment]
oh lol... I turned of my computer and assumed it would build

Time to fix what caused that...

**Comment by James137137** [comment]
http://jenkins.lolnet.co.nz/job/FactionChat/102/artifact/target/FactionChat.jar

**Comment by tuanjr** [comment]
yes, fixed in build 102. Confirm.

**Comment by James137137** [comment]
Thanks. on to the other bugs :D
