### ISSUE TITLE
Officer chat may be malfunctioning + Question on Officer chat (request maybe)

### ISSUE THREAD

**Issue by hoorigan** [James137137/FactionChat#31]
It seems like Officer chat isn't working as intended.  I've included screenshots and a configuration file, as it's probably easier to see it there than in a long-winded explanation.

[Ingame](https://dl.hoorigan.us/fco0.png)
[Console](https://dl.hoorigan.us/fco1.png)
[Config](http://pastebin.com/zuvkDipn)

Also, it seems like a faction's leader should be able to see officer chat, as the leader is technically the top officer.  I'm able to confirm that leaders currently don't see officer chat.

**Comment by James137137** [comment]
found the error

**Comment by James137137** [comment]
http://jenkins.lolnet.co.nz/job/FactionChat/118/

**Comment by hoorigan** [comment]
Seems to be all better now.  Thanks for the quick fix!

**Comment by hoorigan** [comment]
> Also, it seems like a faction's leader should be able to see officer chat, as the leader is technically the top officer. I'm able to confirm that leaders currently don't see officer chat.

Regarding that bit, should I open a separate feature request for that?

**Comment by James137137** [comment]
ummmmmm that is a good question.... Just checking my code..


 if (!ChatMode.IsPlayerMutedTarget(myPlayer, player) && (FactionChatAPI.getPlayerRank(player).equals(Config.LeaderRank)
                    || FactionChatAPI.getPlayerRank(player).equals(Config.OfficerRank)) && ChatMode.getChatMode(myPlayer).equals("OFFICER")) {

in english: each player is checked to see if they are either an **Officer** or a **leader**, however they must have toggled officer chat.

I can't remember why it has to be toggled other than it was requested that way by someone. However if you want I can change that (add something in the config)

**Comment by hoorigan** [comment]
Ok, I see the logic there.  It would definitely be cool if there was something in the config for that, though.  I'd be very greatful to see that added.
