### ISSUE TITLE
Edit Public Chat!

### ISSUE THREAD

**Issue by BliBoy** [James137137/FactionChat#32]
Hello James...I Want To Edit The Public Chat But I Don't Know How Maybe You Could Add Public Chat Format In The Config.. Thanks

**Comment by tuanjr** [comment]
I think this plugin not handle public chat!
You should use other plugins (like Deluxechat or EssentialsChat) to handle public chat

**Comment by BliBoy** [comment]
im ok now thanks...I find out that I can Edit it With The Faction Plugin
ChatFormat

**Comment by James137137** [comment]
tuanjr is correct. FactionChat doesn't handle the public chat
