### ISSUE TITLE
Could not pass event FactionChatPlayerChatEvent to FactionChat

### ISSUE THREAD

**Issue by FatherWh0** [James137137/FactionChat#36]
For some time now my console has been getting spammed with the following stack traces.
https://pastebin.com/kKdLUD06
This has actually been going on for several months but I was busy with other things and ignored it because it would only start occasionally, then stop after 5-10 minutes. Now it's non-stop.
Any help with this would be greatly appreciated.

FactionChat v1.10.4
MassiveCore v2.10.0
paper 1.11.2 # 1104

**Comment by James137137** [comment]
are you using McMMO?

**Comment by FatherWh0** [comment]
Yes, version 1.5.07-SNAPSHOT

**Comment by FatherWh0** [comment]
Here are some more examples in case it's helpful.
Factions Chat version: 1.10.5
McMMO version: 1.5.08

[FCExample.zip](https://github.com/James137137/FactionChat/files/1185954/FCExample.zip)

**Comment by James137137** [comment]
Thanks for the extra info. I'll be updating it very soon

**Comment by James137137** [comment]
okay the latest version of McMMO should have that class... regardless I've made some changes so can't fail
