### ISSUE TITLE
Harmless "attempt to register" severe alert is thrown during load when DontUseAsyncChat is enabled (Tekkit Classic 1.2.5)

### ISSUE THREAD

**Issue by shinji257** [James137137/FactionChat#6]
When loading with DontUseAsyncChat the plugin throws the following.  It appears to be harmless.  It might not be possible to make the alert disappear.  As it stands it doesn't ignore the events at all as the plugin still functions as expected when this alert shows up.
```
[SEVERE] Plugin FactionChat is attempting to register event org/bukkit/event/player/AsyncPlayerChatEvent, which does not exist. Ignoring events registered in class nz.co.lolnet.james137137.FactionChat.FactionChatListener
```

**Comment by James137137** [comment]
Closing issue
